### ISSUE TITLE
Error installing on OSX El Capitan

### ISSUE THREAD

**Issue by justiceamoh** [danielfrg/tsne#6]
I am having issues installing tsne on El Capitan. I've tried using both the pypi source and the git version but get the same error:

```bash
pip install tsne
Collecting tsne
  Using cached tsne-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/1j/l25m3sbs51gbfpynfwny1xvc0000gn/T/pip-build-LDFM7r/tsne/setup.py", line 15, in <module>
        v1, v2, v3 = [float(val) for val in v.split('.')]
    ValueError: need more than 2 values to unpack
```

any ideas how to fix this?

**Comment by danielfrg** [comment]
Thanks for the report.

Should be fixed on https://github.com/danielfrg/tsne/commit/b6188b49b202fe9c168d0434f12f34f3832f0150. New v0.1.2 is on pypi now: https://pypi.python.org/pypi/tsne

Let me know if you are able to test and if it worked or not.

**Comment by justiceamoh** [comment]
Thanks for quickly looking at this @danielfrg. So now, it gets past the requirement checks and fails during the installation (build). The new error which pops up now when i install directly from the git repo:
```bash
running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.5-x86_64-2.7
    creating build/lib.macosx-10.5-x86_64-2.7/tsne
    copying tsne/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/tsne
    copying tsne/_version.py -> build/lib.macosx-10.5-x86_64-2.7/tsne
    UPDATING build/lib.macosx-10.5-x86_64-2.7/tsne/_version.py
    set build/lib.macosx-10.5-x86_64-2.7/tsne/_version.py to 'v0.1.2'
    running build_ext
    building 'bh_sne' extension
    error: unknown file type '.pyx' (from 'tsne/bh_sne.pyx')
```

i tried renaming the file `bh_sne.pyx` to `bh_sne.py` but that didn't work.

**Comment by danielfrg** [comment]
What python are you using? from homebrew? Do you have `cython` installed? I would recommend [anaconda](https://www.continuum.io/downloads) it just worked for me on a new env with this dependencies: https://github.com/danielfrg/tsne/blob/master/environment.yml

**Comment by justiceamoh** [comment]
I created a new environment with the dependencies in your .yml and that works fine (when installed from the git repo). Thanks so much! I was probably missing some dependency.  

I should mention though that the pypi version still throws an error about versioneer even though it's installed:
```bash
Collecting tsne
  Using cached tsne-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/1j/l25m3sbs51gbfpynfwny1xvc0000gn/T/pip-build-_r263k/tsne/setup.py", line 9, in <module>
        import versioneer
    ImportError: No module named versioneer
```

**Comment by danielfrg** [comment]
I just fixed the versioneer bug and you should be able to pip install it.

Closing since the issue was fixed.
Thanks!
